export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const ADD_ROLE = 'ADD_ROLE'
export const ADD_DISPLAY_NAME = 'ADD_DISPLAY_NAME'
export const ADD_PROFILE_DATA = 'ADD_PROFILE_DATA'
export const CHANGE_PROFILE_URL = 'CHANGE_PROFILE_URL'